### 로그인 API
POST {{url}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@dandi.com",
  "password": "Test1234!"
}

### 회원가입 API
POST {{url}}/api/v1/auth/signup
Content-Type: application/json

{
  "email": "test@dandi.com",
  "password": "Test1234!",
  "nickname": "진우 집사",
  "gender": "남성",
  "birth": "2026-07-12",
  "height": 175,
  "weight": 80
}

### 이메일 인증 API
POST {{url}}/api/v1/auth/email-verification
Content-Type: application/json

{
  "email": "example@naver.com"
}

### 이메일 인증 확인 API
POST {{url}}/api/v1/auth/email-verification/confirm
Content-Type: application/json

{
  "email": "example@naver.com",
  "verificationCode": 123456
}

### access token 재발급 API
POST {{url}}/api/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}