### 고양이 생성 API
POST {{url}}/api/v1/cats
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "초코",
  "breakfastHour": null,
  "lunchHour": 12,
  "dinnerHour": 19
}

### 고양이 체형 API
GET {{url}}/api/v1/cats
Authorization: Bearer {{accessToken}}

### 고양이 애니메이션 API
GET {{url}}/api/v1/cats/animations
Authorization: Bearer {{accessToken}}