### 비밀번호 변경 API
PATCH {{url}}/api/v1/users/me/password
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "password": "Password123!",
  "newPassword": "NewPassword123!"
}

### 프로필 API
GET {{url}}/api/v1/users/me
Authorization: Bearer {{accessToken}}